name: norway_roznama_new_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  get_it: ^8.0.3
  flutter_launcher_icons: ^0.14.2
  mobile_scanner: ^6.0.5
  fancy_shimmer_image: ^2.0.3
  path_provider: ^2.1.4
  share_plus: ^10.0.0
  percent_indicator: ^4.2.4
  geolocator: ^13.0.2
  intl: ^0.20.2
  flutter_compass: ^0.8.1
  flutter_html: ^3.0.0-beta.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  shared_preferences: ^2.5.1
  audioplayers: ^6.2.0
  flutter_timezone: ^4.1.0
  firebase_core: ^2.24.2
  jhijri: ^1.0.0
  device_info_plus: ^11.3.0
  android_intent_plus: ^5.3.0
  screenshot: ^3.0.0
  pdf: ^3.11.3
  firebase_messaging: ^14.7.10
  file_picker: ^10.1.0
  media_scanner: ^2.2.0
  hijri: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/icons/
    - assets/sounds/alafasi.mp3

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 100