// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUQxztJzo2xIQRz6qeNi-6OgDBfWUpJk',
    appId: '1:123668889484:web:e20899b640eecb72a420a9',
    messagingSenderId: '123668889484',
    projectId: 'norway-roznama',
    authDomain: 'norway-roznama.firebaseapp.com',
    storageBucket: 'norway-roznama.firebasestorage.app',
    measurementId: 'G-KXSQ512FRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXCY7wbMt24R7F_Vl_i7HdJ_iTMwwQxY',
    appId: '1:123668889484:android:b1efb33c6d20a05ca420a9',
    messagingSenderId: '123668889484',
    projectId: 'norway-roznama',
    storageBucket: 'norway-roznama.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpgAfPt5SAt_8o89ai6el3KKr_Qk_degs',
    appId: '1:123668889484:ios:953f5f27f2f8e092a420a9',
    messagingSenderId: '123668889484',
    projectId: 'norway-roznama',
    storageBucket: 'norway-roznama.firebasestorage.app',
    iosBundleId: 'com.example.norwayRoznamaNewProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpgAfPt5SAt_8o89ai6el3KKr_Qk_degs',
    appId: '1:123668889484:ios:953f5f27f2f8e092a420a9',
    messagingSenderId: '123668889484',
    projectId: 'norway-roznama',
    storageBucket: 'norway-roznama.firebasestorage.app',
    iosBundleId: 'com.example.norwayRoznamaNewProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCUQxztJzo2xIQRz6qeNi-6OgDBfWUpJk',
    appId: '1:123668889484:web:41a0836f3f05559da420a9',
    messagingSenderId: '123668889484',
    projectId: 'norway-roznama',
    authDomain: 'norway-roznama.firebaseapp.com',
    storageBucket: 'norway-roznama.firebasestorage.app',
    measurementId: 'G-V4FK49T98S',
  );
}
